app/forms/contact_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.fields.html5 import EmailField
from wtforms.validators import required, optional, Email


class ContactForm(FlaskForm):
    name = StringField(label='Name', validators=[required()])
    company = StringField(label='Company', validators=[optional()])
    email = EmailField(label='Email address', validators=[required(), Email(message='Email address is not valid')], id='formEmail', render_kw={'placeholder': 'name@emailaddress.com'})
    question = TextAreaField(label='Question?', validators=[optional()], render_kw={'rows': 4})

app/__init__.py
import os
from flask import Flask
from flask_wtf.csrf import CSRFProtect


def access_secrets():
    from google.cloud import secretmanager

    client = secretmanager.SecretManagerServiceClient()

    secrets = {
        'secret_key': 'projects/123181321826/secrets/SECRET_KEY/versions/latest',
        'sendgrid_api_key': 'projects/123181321826/secrets/SENDGRID_API_KEY/versions/latest'
    }

    ret = {}
    for key, value in secrets.items():
        response = client.access_secret_version(request={"name": value})
        payload = response.payload.data.decode("UTF-8")
        ret[key] = payload

    return ret


csrf = CSRFProtect()

def create_app(testing=False):
    app = Flask(__name__)

    flask_env = os.getenv("FLASK_ENV", 'production')

    from app import config

    if flask_env == 'production':
        secrets = access_secrets()
        app.config.from_object(config.ProductionConfig)

        app.config['SECRET_KEY'] = secrets['secret_key']
        app.config['SENDGRID_API_KEY'] = secrets['sendgrid_api_key']

    else:
        app.config['SECRET_KEY'] = os.getenv('SECRET_KEY', None)
        app.config['SENDGRID_API_KEY'] = os.getenv('SENDGRID_API_KEY')

        if testing or flask_env == 'testing':
            app.config.from_object(config.TestingConfig)
        elif flask_env == 'development':
            app.config.from_object(config.DevelopmentConfig)

    # init CSRF protection
    csrf.init_app(app)

    # Import and register blueprints
    from app.routes import route
    app.register_blueprint(route)

    return app

app/routes.py
import sendgrid
from sendgrid.helpers.mail import Mail, Email, To, Content
from flask import Blueprint, render_template, request, jsonify, make_response, current_app as app
from app.forms.contact_form import ContactForm


route = Blueprint("route", __name__)

@route.route("/", methods=['GET', 'POST'])
def index():
    form = ContactForm()

    if request.method == 'GET':
        return render_template('index.html', form=form)

    elif request.method == 'POST':
        if form.validate_on_submit():
            name = form.name.data
            company = form.company.data
            email = form.email.data
            question = request.form['question']

            sg = sendgrid.SendGridAPIClient(api_key=app.config['SENDGRID_API_KEY'])
            from_email = Email('contact-me@greenrangeproducts.com')
            to_email = To('walker@greenrangeproducts.com')
            company = company if company else 'NO_COMPANY_PROVIDED'
            body = question if question else 'NO_QUESTION_PROVIDED'
            subject = f"'{name}' from '{company}' has requested information"
            content = Content("text/plain", body)
            mail = Mail(from_email, to_email, subject, content)

            mail_json = mail.get()
            response = sg.client.mail.send.post(request_body=mail_json)


            return make_response(jsonify({'message': 'Successfully submitted'}), 200)
        else:
            print(f'errors: {form.errors}')

        return make_response(jsonify({'message': form.errors}), 200)

@route.app_errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <link rel="stylesheet" href="{{ url_for('static', filename='css/global.css') }}">

  {% block css %}
  {% endblock %}

  {% block title %}
  <title>Green Range</title>
  {% endblock %}

  {% block favicon %}
  {% endblock %}
</head>

<body class="background-secondary" style="position: relative;">
<div id="content">
  {% block content %}
  {% endblock %}
</div>
<footer id="footer">
  <div class="container">
    <p class="float-right">
      {% block footer_link %}
        <button onclick="topFunction()" id="topBtn" class="btn btn-outline-secondary button-top-reveal"
          title="Go to top">Back to Top</button>
      {% endblock %}
    </p>
  </div>
</footer>

<script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
</script>

<script type="text/javascript" src="{{ url_for('static', filename='js/global.js') }}"></script>
<script type="text/jacascript" src="{{ url_for('static', filename='js/jquery_easing.js') }}"></script>

{% block scripts %}
{% endblock %}
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/fonts/all.min.css') }}">
{% endblock %}

{% block content %}
<div id="pageTop"></div>

<div id="nav">
  <nav
    class="fixed-top d-none d-xl-block p-3 text-white primary-color"
  style="width: 12%; height: 100%">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <span class="fs-4">Green Range</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <a href="#about" class="nav-link text-white" aria-current="page">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#about"/></svg>
        About
      </a>
    </li>
    <li>
      <a href="#whatDoIDo" class="nav-link text-white">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#whatDoIDo"/></svg>
        Service
      </a>
    </li>
    <li>
      <a href="#contact" class="nav-link text-white">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#contact"/></svg>
        Contact
      </a>
    </li>
  </ul>
  </nav>
</div>

<div class="container px-4 py-5 my-5 text-center">
  <h1 class="display-2 fw-bold">Green Range, LLC</h1>
  <div class="col-lg-6 mx-auto">
    <h4>Sustainable foodservice products</h4>
  </div>
</div>

<div class="heroes-divider"></div>

<div id="about" class="container col-xxl-8 px-4 py-5 my-5">
  <div class="row align-items-center g-5 py-5 rounded-3 border shadow-lg">
    <h1 class="display-5 fw-bold text-center border-bottom">About</h1>
    <p class="lead mb-1">
      My name is Walker Sorlie, and I am the owner and operator of Green Range, LLC! Born and raised here in
      Bend, Oregon, I have a deep-seated love of everything Bend has to offer, and as Bend continues to grow, I
      want to continue to provide <strong>sustainable</strong> and <strong>economically-accessible</strong>
      products for our food service industry.
    </p>
  </div>
</div>

<div class="heroes-divider"></div>

<div id="whatDoIDo" class="container col-xxl-8 px-4 py-5 my-5">
  <div class="row align-items-center g-5 py-5 rounded-3 border shadow-lg">
    <h1 class="display-5 fw-bold text-center border-bottom">What Do I Do?</h1>
    <p class="lead text-center">
      I manage the entire lifecycle of your inventory and ordering needs! I purchase the products you want, store
      them in my own personal storage space, and I deliver them according to your schedule and needs.
    </p>
    <div class="col-10 col-sm-8 col-lg-6 list-group">
      <div class="list-group lead" id="list-tab" role="tablist">
        <a class="list-group-item list-group-item-action active" id="list-research-list" data-bs-toggle="list"
          href="#list-research" role="tab" aria-controls="list-research">Research</a>
        <a class="list-group-item list-group-item-action" id="list-ordering-list" data-bs-toggle="list"
          href="#list-ordering" role="tab" aria-controls="list-ordering">Ordering</a>
        <a class="list-group-item list-group-item-action" id="list-receiving-list" data-bs-toggle="list"
          href="#list-receiving" role="tab" aria-controls="list-receiving">Receiving</a>
        <a class="list-group-item list-group-item-action" id="list-storage-list" data-bs-toggle="list"
          href="#list-storage" role="tab" aria-controls="list-storage">Storage</a>
        <a class="list-group-item list-group-item-action" id="list-delivery-list" data-bs-toggle="list"
          href="#list-delivery" role="tab" aria-controls="list-delivery">Delivery</a>
        <a class="list-group-item list-group-item-action" id="list-problems-list" data-bs-toggle="list"
          href="#list-problems" role="tab" aria-controls="list-problems">Problem Resolving</a>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="tab-content lead" id="nav-tabContent">
        <div class="tab-pane fade show active" id="list-research" role="tabpanel"
          aria-labelledby="list-research-list">I keep up-to-date on the latest compostable products and always
          take the time to find you the best price</div>
        <div class="tab-pane fade" id="list-ordering" role="tabpanel" aria-labelledby="list-profile-list">I make
          purchase orders and interact with suppliers and distributors so you don't have to</div>
        <div class="tab-pane fade" id="list-receiving" role="tabpanel" aria-labelledby="list-receiving-list">I
          receive products shipments and check that everything arrived in good condition.</div>
        <div class="tab-pane fade" id="list-storage" role="tabpanel" aria-labelledby="list-storage-list">I
          warehouse and store all of the products so you don't have to try and find space to fit that fifth box of
          cups</div>
        <div class="tab-pane fade" id="list-delivery" role="tabpanel" aria-labelledby="list-delivery-list">I
          deliver the products you desire on your schedule. So whenever you make an order, I can deliver that day,
          the next day, or whenever you'd like</div>
        <div class="tab-pane fade" id="list-problems" role="tabpanel" aria-labelledby="list-problems-list">I resolve all
          problems that may arise in this entire warehouseing lifecycle:
          <ul>
            <li>Damaged product: Handle getting replacements</li>
            <li>Incorrect items sent: Handle getting correct items shipped</li>
            <li>Items out of stock: Find suitable interim replacement items</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="heroes-divider"></div>

<div id="contact" class="container col-xxl-8 px-4 py-5 my-5">
  <div class="g-5 py-5 rounded-3 border shadow-lg">
    <div class="row">
      <h1 class="display-5 fw-bold text-center">Contact Me for Inquiries</h1>
      <p class="lead text-center">
        Please fill our this form or contact me directly at <a
        href="mailto:contact-me@greenrangeproducts.com">contact-me@greenrangeproducts.com</a>.
      </p>
    </div>
    <form id="contactForm" action="{{ url_for('route.index') }}" method="post">
      {{ form.csrf_token }}
      <div class="row justify-content-center">
        <div class="col-4 mb-3">
          {{ form.name.label(class_="form-label") }}
          {{ form.name(class_="form-control") }}
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-4 mb-3">
          {{ form.company.label(class_="form-label") }}
          {{ form.company(class_="form-control") }}
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-4 mb-3">
          {{ form.email.label(class_="form-label") }}
          {{ form.email(class_="form-control") }}
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-6 mb-3">
          {{ form.question.label(class_="form-label") }}
          {{ form.question(class_="form-control") }}
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-4 mb-3">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </form>
    <div class="row text-center">
      <div id="contactFormSubmitted" style="display: none;">
        <p class="lead">
          You have submitted your contact request.
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/index.js') }}"></script>
{% endblock %}